package com.example

import android.util.Log
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.concurrent.TimeUnit

object GeminiService {
    private const val TAG = "GeminiService"
    
    private val client = OkHttpClient.Builder()
        .connectTimeout(60, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .writeTimeout(60, TimeUnit.SECONDS)
        .build()

    suspend fun generateContent(
        prompt: String,
        systemInstruction: String? = null,
        useSearch: Boolean = true
    ): String = withContext(Dispatchers.IO) {
        val apiKey = BuildConfig.GEMINI_API_KEY
        if (apiKey.isEmpty() || apiKey == "MY_GEMINI_API_KEY") {
            Log.e(TAG, "Gemini API key is not set or using the default placeholder.")
            return@withContext "Error: Gemini API key is not configured in the Secrets panel."
        }

        val url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent?key=$apiKey"
        
        try {
            val jsonBody = JSONObject().apply {
                // Contents array
                val contents = JSONArray().apply {
                    val contentObj = JSONObject().apply {
                        val parts = JSONArray().apply {
                            val partObj = JSONObject().apply {
                                put("text", prompt)
                            }
                            put(partObj)
                        }
                        put("parts", parts)
                    }
                    put(contentObj)
                }
                put("contents", contents)

                // Generation Config
                val generationConfig = JSONObject().apply {
                    put("temperature", 0.5)
                }
                put("generationConfig", generationConfig)

                // System Instruction if provided
                if (!systemInstruction.isNullOrBlank()) {
                    val systemInstructionObj = JSONObject().apply {
                        val parts = JSONArray().apply {
                            val partObj = JSONObject().apply {
                                put("text", systemInstruction)
                            }
                            put(partObj)
                        }
                        put("parts", parts)
                    }
                    put("systemInstruction", systemInstructionObj)
                }

                // Add search grounding tool if enabled
                if (useSearch) {
                    val tools = JSONArray().apply {
                        val tool = JSONObject().apply {
                            put("googleSearch", JSONObject())
                        }
                        put(tool)
                    }
                    put("tools", tools)
                }
            }

            val requestBody = jsonBody.toString().toRequestBody("application/json".toMediaType())
            val request = Request.Builder()
                .url(url)
                .post(requestBody)
                .build()

            client.newCall(request).execute().use { response ->
                val bodyString = response.body?.string() ?: ""
                Log.d(TAG, "Response Code: ${response.code}")
                
                if (!response.isSuccessful) {
                    Log.e(TAG, "Request failed: $bodyString")
                    return@withContext "Error callback: HTTP ${response.code} - ${response.message}"
                }

                val responseJson = JSONObject(bodyString)
                val candidates = responseJson.optJSONArray("candidates")
                if (candidates != null && candidates.length() > 0) {
                    val firstCandidate = candidates.getJSONObject(0)
                    val content = firstCandidate.optJSONObject("content")
                    if (content != null) {
                        val parts = content.optJSONArray("parts")
                        if (parts != null && parts.length() > 0) {
                            val text = parts.getJSONObject(0).optString("text")
                            return@withContext text
                        }
                    }
                }
                return@withContext "Error: No valid content was generated by Gemini."
            }
        } catch (e: Exception) {
            Log.e(TAG, "Exception during generateContent", e)
            return@withContext "Error details: ${e.localizedMessage ?: "Unknown connection error"}"
        }
    }
}
